cresta_aulas:
    resource: "@CrestaAulasBundle/Resources/config/routing.yml"
    prefix:   /
#Agregado de FOSUser // by Ale
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#Fin Agregado FOSUser

<<<<<<< HEAD
#Agregado del PdfBundle

pdf_file:
    #resource: "@PsPdfBundle/Resources/config/pdf.xml"
    #prefix:   /pdf

    pattern: /alerta/{name}
    defaults: { _controller: Cresta:AulasBundle:PdfController:helloAction }

#Fin Agregado PDFbundle
=======
>>>>>>> cf2c2fa5c1cf37852147d19fae7945e9d51105c2
