aulas_administrador:
    path:     /
    defaults: { _controller: "CrestaAulasBundle:Administrador:index" }

aulas_administrador_show:
    path:     /{id}/show
    defaults: { _controller: "CrestaAulasBundle:Administrador:show" }

aulas_administrador_new:
    path:     /new
    defaults: { _controller: "CrestaAulasBundle:Administrador:new" }

aulas_administrador_create:
    path:     /create
    defaults: { _controller: "CrestaAulasBundle:Administrador:create" }
    requirements: { _method: post }

aulas_administrador_edit:
    path:     /{id}/edit
    defaults: { _controller: "CrestaAulasBundle:Administrador:edit" }

aulas_administrador_update:
    path:     /{id}/update
    defaults: { _controller: "CrestaAulasBundle:Administrador:update" }
    requirements: { _method: post|put }

aulas_administrador_delete:
    path:     /{id}/delete
    defaults: { _controller: "CrestaAulasBundle:Administrador:delete" }
    requirements: { _method: post|delete }
