aulas_alerta:
    path:     /
    defaults: { _controller: "CrestaAulasBundle:Alerta:index" }

aulas_alerta_show:
    path:     /{id}/show
    defaults: { _controller: "CrestaAulasBundle:Alerta:show" }

aulas_alerta_new:
    path:     /new
    defaults: { _controller: "CrestaAulasBundle:Alerta:new" }

aulas_alerta_create:
    path:     /create
    defaults: { _controller: "CrestaAulasBundle:Alerta:create" }
    requirements: { _method: post }

aulas_alerta_edit:
    path:     /{id}/edit
    defaults: { _controller: "CrestaAulasBundle:Alerta:edit" }

aulas_alerta_update:
    path:     /{id}/update
    defaults: { _controller: "CrestaAulasBundle:Alerta:update" }
    requirements: { _method: post|put }

aulas_alerta_delete:
    path:     /{id}/delete
    defaults: { _controller: "CrestaAulasBundle:Alerta:delete" }
    requirements: { _method: post|delete }
