aulas_docente:
    path:     /
    defaults: { _controller: "CrestaAulasBundle:Docente:index" }

aulas_docente_show:
    path:     /{id}/show
    defaults: { _controller: "CrestaAulasBundle:Docente:show" }

aulas_docente_new:
    path:     /new
    defaults: { _controller: "CrestaAulasBundle:Docente:new" }

aulas_docente_create:
    path:     /create
    defaults: { _controller: "CrestaAulasBundle:Docente:create" }
    requirements: { _method: post }

aulas_docente_edit:
    path:     /{id}/edit
    defaults: { _controller: "CrestaAulasBundle:Docente:edit" }

aulas_docente_update:
    path:     /{id}/update
    defaults: { _controller: "CrestaAulasBundle:Docente:update" }
    requirements: { _method: post|put }

aulas_docente_delete:
    path:     /{id}/delete
    defaults: { _controller: "CrestaAulasBundle:Docente:delete" }
#    requirements: { _method: post|delete }
