#cresta_aulas_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: CrestaAulasBundle:Default:index }

_acercade:
    path:     /acercade
    defaults: { _controller: CrestaAulasBundle:Default:acercade }

_ayuda:
    path:     /ayuda
    defaults: { _controller: CrestaAulasBundle:Default:ayuda }