_homepage:
    path:     /
    defaults: { _controller: CrestaAulasBundle:Default:index }

_acercade:
    path:     /acercade
    defaults: { _controller: CrestaAulasBundle:Default:acercade }

_ayuda:
    path:     /ayuda
    defaults: { _controller: CrestaAulasBundle:Default:ayuda }

CrestaAulasBundle_alerta:
    resource: "@CrestaAulasBundle/Resources/config/routing/alerta.yml"
    prefix:   /alerta

CrestaAulasBundle_aula:
    resource: "@CrestaAulasBundle/Resources/config/routing/aula.yml"
    prefix:   /aula

CrestaAulasBundle_actividad:
    resource: "@CrestaAulasBundle/Resources/config/routing/actividad.yml"
    prefix:   /actividad

CrestaAulasBundle_curso:
    resource: "@CrestaAulasBundle/Resources/config/routing/curso.yml"
    prefix:   /curso

CrestaAulasBundle_tarea:
    resource: "@CrestaAulasBundle/Resources/config/routing/tarea.yml"
    prefix:   /tarea