_homepage:
    path:     /
    defaults: { _controller: CrestaAulasBundle:Default:index }

_acercade:
    path:     /acercade
    defaults: { _controller: CrestaAulasBundle:Default:acercade }

_ayuda:
    path:     /ayuda
    defaults: { _controller: CrestaAulasBundle:Default:ayuda }

_imprimir:
    path:     /imprimir
    defaults: { _controller: CrestaAulasBundle:Default:imprimir }
#    param:    { module: listado, action: imprimir}


  
