_homepage:
    path:     /
    defaults: { _controller: CrestaAulasBundle:Default:index }

_acercade:
    path:     /acercade
    defaults: { _controller: CrestaAulasBundle:Default:acercade }

_ayuda:
    path:     /ayuda
    defaults: { _controller: CrestaAulasBundle:Default:ayuda }

CrestaAulasBundle_alerta:
    resource: "@CrestaAulasBundle/Resources/config/routing/alerta.yml"
    prefix:   /alerta