parameters:
#    cresta_aulas.example.class: Cresta\AulasBundle\Example
	cresta.controller.movimiento.class: Cresta\AulasBundle\Controller\MoviemientoController
services:
#    cresta_aulas.example:
#        class: %cresta_aulas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
	cresta.movimiento.controller:
		clas: "%cresta.controller.movimiento.class%"