# src/Acme/UserBundle/Resources/config/services.yml
services:
    cresta_aulasbundle_user.registration.form.type:
        class:     Cresta\AulasBundle\Form\RegistrationFormType
        arguments:     [%fos_user.model.user.class%]
        tags:
            - { name:     form.type, alias:     cresta_aulasbundle_user_registration }

    cresta_aulasbundle_user.profile.form.type:
        class:     Cresta\AulasBundle\Form\ProfileFormType
        arguments:     [%fos_user.model.user.class%]
        tags:
            - { name:     form.type, alias:     cresta_aulasbundle_user_profile }