<?php

// This file is automatically generated and modified by phpMyBackupPro v.2.3

$CONF['sql_user']=htmlspecialchars_decode("root");
$CONF['sql_passwd']=htmlspecialchars_decode("kapanga");
$CONF['sql_host']=htmlspecialchars_decode("localhost");
$CONF['sql_db']=htmlspecialchars_decode("symfony");
$CONF['ftp_use']=htmlspecialchars_decode("0");
$CONF['allow_dir_backup']=htmlspecialchars_decode("0");
$CONF['email_use']=htmlspecialchars_decode("0");
$CONF['sitename']=htmlspecialchars_decode("mySite");
$CONF['lang']=htmlspecialchars_decode("english");
$CONF['import_error']=htmlspecialchars_decode("1");
$CONF['no_login']=htmlspecialchars_decode("0");
$CONF['login']=htmlspecialchars_decode("0");
$CONF['dir_backup']=htmlspecialchars_decode("0");
$CONF['dir_rec']=htmlspecialchars_decode("1");
$CONF['email']=htmlspecialchars_decode("");
$CONF['ftp_pasv']=htmlspecialchars_decode("1");
$CONF['ftp_del']=htmlspecialchars_decode("1");
$CONF['ftp_server']=htmlspecialchars_decode("example.net");
$CONF['ftp_user']=htmlspecialchars_decode("");
$CONF['ftp_passwd']=htmlspecialchars_decode("");
$CONF['ftp_path']=htmlspecialchars_decode("example/");
$CONF['ftp_port']=htmlspecialchars_decode("21");
$CONF['date']=htmlspecialchars_decode("%d.%m.%Y %H:%M Uhr");
$CONF['del_time']=htmlspecialchars_decode("7");
$CONF['del_number']=htmlspecialchars_decode("5");
$CONF['timelimit']=htmlspecialchars_decode("600");
$CONF['confirm']=htmlspecialchars_decode("1");
$CONF['stylesheet']=htmlspecialchars_decode("standard");

$PMBP_SYS_VAR['last_scheduled']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['this_login']=htmlspecialchars_decode("06.10.2014 13:02 Uhr (IP: 127.0.0.1)");
$PMBP_SYS_VAR['last_login']=htmlspecialchars_decode("05.10.2014 04:04 Uhr (IP: 127.0.0.1)");
$PMBP_SYS_VAR['dir_lists']=htmlspecialchars_decode("1");
$PMBP_SYS_VAR['memory_limit']=htmlspecialchars_decode("4000000");
$PMBP_SYS_VAR['except_tables']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['scheduled_debug']=htmlspecialchars_decode("0");
$PMBP_SYS_VAR['schedule_all_dbs']=htmlspecialchars_decode("0");
$PMBP_SYS_VAR['ftp_timeout']=htmlspecialchars_decode("10");
$PMBP_SYS_VAR['dir_email_backup']=htmlspecialchars_decode("0");
$PMBP_SYS_VAR['C_disable_config']=htmlspecialchars_decode("0");
$PMBP_SYS_VAR['C_disable_sqlquery']=htmlspecialchars_decode("0");
$PMBP_SYS_VAR['B_backup_chmod']=htmlspecialchars_decode("0700");
$PMBP_SYS_VAR['F_dbs']=htmlspecialchars_decode("symfony");
$PMBP_SYS_VAR['F_comment']=htmlspecialchars_decode("Alta base de datos papa");
$PMBP_SYS_VAR['F_tables']=htmlspecialchars_decode("on");
$PMBP_SYS_VAR['F_data']=htmlspecialchars_decode("on");
$PMBP_SYS_VAR['F_drop']=htmlspecialchars_decode("on");
$PMBP_SYS_VAR['F_compression']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['F_ftp_dirs']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['F_ftp_dirs_2']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['F_packed']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['F_updates']=htmlspecialchars_decode("1");
$PMBP_SYS_VAR['F_ffadd']=htmlspecialchars_decode("1");
$PMBP_SYS_VAR['EXS_scheduled_file']=htmlspecialchars_decode("???.php");
$PMBP_SYS_VAR['EXS_scheduled_dir']=htmlspecialchars_decode("0");
$PMBP_SYS_VAR['EXS_period']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['security_key']=htmlspecialchars_decode("b9bd91943deb2d6e53f97297fea0317b");

?>