<?php

namespace Cresta\AulasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertaRepository extends EntityRepository
{
}
