<?php

namespace Cresta\AulasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservaDeRecursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaDeRecursoRepository extends EntityRepository
{
}
